from tkinter import *
root = Tk()
root.title('ButtonStyle')
root.minsize(height=150, width=580)

Label(root, text='borderwidth = 0').grid(row=0, column=0)
Label(root, text=' ', width=2).grid(row=0, column=1)
Button(root, text = 'raised', relief=RAISED,width=10, borderwidth=0).grid(row=0, column=2)
Label(root, text=' ', width=2).grid(row=0, column=3)
Button(root, text = 'sunken', relief=SUNKEN,width=10, borderwidth=0).grid(row=0, column=4)
Label(root, text=' ', width=2).grid(row=0, column=5)
Button(root, text = 'flat', relief=FLAT,width=10, borderwidth=0).grid(row=0, column=6)
Label(root, text=' ', width=2).grid(row=0, column=7)
Button(root, text = 'ridge', relief=RIDGE,width=10, borderwidth=0).grid(row=0, column=8)
Label(root, text=' ', width=2).grid(row=0, column=9)
Button(root, text = 'groove', relief=GROOVE,width=10, borderwidth=0).grid(row=0, column=10)
Label(root, text=' ', width=2).grid(row=0, column=11)
Button(root, text = 'solid', relief=SOLID,width=10, borderwidth=0).grid(row=0, column=12)

Label(root, text='borderwidth = 1').grid(row=1, column=0)
Label(root, text=' ', width=2).grid(row=1, column=1)
Button(root, text = 'raised', relief=RAISED,width=10, borderwidth=1).grid(row=1, column=2)
Label(root, text=' ', width=2).grid(row=1, column=3)
Button(root, text = 'sunken', relief=SUNKEN,width=10, borderwidth=1).grid(row=1, column=4)
Label(root, text=' ', width=2).grid(row=1, column=5)
Button(root, text = 'flat', relief=FLAT,width=10, borderwidth=1).grid(row=1, column=6)
Label(root, text=' ', width=2).grid(row=1, column=7)
Button(root, text = 'ridge', relief=RIDGE,width=10, borderwidth=1).grid(row=1, column=8)
Label(root, text=' ', width=2).grid(row=1, column=9)
Button(root, text = 'groove', relief=GROOVE,width=10, borderwidth=1).grid(row=1, column=10)
Label(root, text=' ', width=2).grid(row=1, column=11)
Button(root, text = 'solid', relief=SOLID,width=10, borderwidth=1).grid(row=1, column=12)

Label(root, text='borderwidth = 2').grid(row=2, column=0)
Label(root, text=' ', width=2).grid(row=2, column=1)
Button(root, text = 'raised', relief=RAISED,width=10, borderwidth=2).grid(row=2, column=2)
Label(root, text=' ', width=2).grid(row=2, column=3)
Button(root, text = 'sunken', relief=SUNKEN,width=10, borderwidth=2).grid(row=2, column=4)
Label(root, text=' ', width=2).grid(row=2, column=5)
Button(root, text = 'flat', relief=FLAT,width=10, borderwidth=2).grid(row=2, column=6)
Label(root, text=' ', width=2).grid(row=2, column=7)
Button(root, text = 'ridge', relief=RIDGE,width=10, borderwidth=2).grid(row=2, column=8)
Label(root, text=' ', width=2).grid(row=2, column=9)
Button(root, text = 'groove', relief=GROOVE,width=10, borderwidth=2).grid(row=2, column=10)
Label(root, text=' ', width=2).grid(row=2, column=11)
Button(root, text = 'solid', relief=SOLID,width=10, borderwidth=2).grid(row=2, column=12)

Label(root, text='borderwidth = 3').grid(row=3, column=0)
Label(root, text=' ', width=2).grid(row=3, column=1)
Button(root, text = 'raised', relief=RAISED,width=10, borderwidth=3).grid(row=3, column=2)
Label(root, text=' ', width=2).grid(row=3, column=3)
Button(root, text = 'sunken', relief=SUNKEN,width=10, borderwidth=3).grid(row=3, column=4)
Label(root, text=' ', width=2).grid(row=3, column=5)
Button(root, text = 'flat', relief=FLAT,width=10, borderwidth=3).grid(row=3, column=6)
Label(root, text=' ', width=2).grid(row=3, column=7)
Button(root, text = 'ridge', relief=RIDGE,width=10, borderwidth=3).grid(row=3, column=8)
Label(root, text=' ', width=2).grid(row=3, column=9)
Button(root, text = 'groove', relief=GROOVE,width=10, borderwidth=3).grid(row=3, column=10)
Label(root, text=' ', width=2).grid(row=3, column=11)
Button(root, text = 'solid', relief=SOLID,width=10, borderwidth=3).grid(row=3, column=12)

Label(root, text='borderwidth = 4').grid(row=4, column=0)
Label(root, text=' ', width=2).grid(row=4, column=1)
Button(root, text = 'raised', relief=RAISED,width=10, borderwidth=4).grid(row=4, column=2)
Label(root, text=' ', width=2).grid(row=4, column=3)
Button(root, text = 'sunken', relief=SUNKEN,width=10, borderwidth=4).grid(row=4, column=4)
Label(root, text=' ', width=2).grid(row=4, column=5)
Button(root, text = 'flat', relief=FLAT,width=10, borderwidth=4).grid(row=4, column=6)
Label(root, text=' ', width=2).grid(row=4, column=7)
Button(root, text = 'ridge', relief=RIDGE,width=10, borderwidth=4).grid(row=4, column=8)
Label(root, text=' ', width=2).grid(row=4, column=9)
Button(root, text = 'groove', relief=GROOVE,width=10, borderwidth=4).grid(row=4, column=10)
Label(root, text=' ', width=2).grid(row=4, column=11)
Button(root, text = 'solid', relief=SOLID,width=10, borderwidth=4).grid(row=4, column=12)
root.mainloop()